name : Postman Collection Workflow

on:
  push : 
    branches : [main]
  workflow_dispatch:
  schedule:
    - cron : 30 2 * * * #8 AM IST
    - cron : 00 14 * * * # 730 PM IST Every Day
    - cron : 00 06 * * * #1130 AM IST Monday to Friday

jobs:
  run-postman-tests:
    run-on: ubuntu-latest  

    steps:
    
      -name: checkout the code
       uses: actions/checkout@v4.2.2
       
      -name: install node.js and npm
       uses: actions/setup-node@v3.9.1
       with:
         node-version: 22
    
       -name: Install newman and Html-extra globally
        run:
             npm install -g newman
             npm install -g newman-reporter-htmlextra
        
        -name: Run the Postman Collection with newman
         run: | 
               newman run 'Inwarranty-flow Collection.postman_collection.json' \
               -e QA.postman_environment.json \
               -d testdata.csv \
               -r htmlextra

             
             
